### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.externals.joblib'

### ISSUE THREAD

**Issue by gentrexha** [skylergrammer/SimulatedAnnealing#5]
When trying to run the example I get this error message:

```
  File "...\lib\site-packages\simulated_annealing\optimize.py", line 9, in <module>
    from sklearn.externals.joblib import Parallel, delayed
ModuleNotFoundError: No module named 'sklearn.externals.joblib'
```

> The issue is because sklearn.externals.joblib is deprecated from scikit-learn 0.21 onwards and has been removed in 0.23 of scikit-learn. Downgrading scikit-learn to 0.20.1 removes the error message. While, v0.21.1 of scikit-learn doesn't throw up the error, it does throw a deprecation warning.

Would be great to have the requirements.txt updated.

**Comment by skylergrammer** [comment]
Gent, thanks for opening this issue. I've pulled out the dependency on scikit-learn's external joblib. You should have no issue with the updated versions of scikit-learn.
